### PR TITLE
CSS Optimisations for small screen: Fix token and header sections

### LINKED ISSUE #594: Token on admin page doesn’t render correctly on smaller screens
The token on smaller screens look messed up.

5B3ED1FB-691A-4ED5-9171-2A01FF0CE5F5

### PR DESCRIPTION
**Pull request by navaneeth-spotnana**
There were minor css issues on smaller screens, which are fixed.

Also resolves #594

### CODE REVIEW

File: simplq/src/components/pages/Admin/Token.jsx [hunk 1]
```diff
@@ -106,8 +106,8 @@ function Token({ token }) {
           <div className={styles['token-icon-set']}>
             <CallButton />
             <NotifyButton />
-            <RemoveButton />
           </div>
+          <RemoveButton />
```
Comment (daltonfury42) [inline simplq/src/components/pages/Admin/Token.jsx:110]: Remove button should have been outside the icon set

File: simplq/src/components/common/QueueInfo/QueueInfo.module.scss [hunk 2]
```diff
@@ -3,14 +3,12 @@
...
   flex-direction: column;
-  padding: 0.5rem 2rem;
-  max-width: 35rem;
+  padding: 2rem 0rem;
 
   .detail-row {
     display: flex;
     align-items: center;
     justify-content: space-between;
-    height: 1.5rem;
```
Comment (daltonfury42) [inline simplq/src/components/common/QueueInfo/QueueInfo.module.scss:13]: This was causing the text to overlap on smaller screens
Screenshot 2021-03-27 at 11 13 45 AM

File: simplq/src/components/pages/Admin/admin.module.scss [hunk 3]
```diff
@@ -105,8 +106,10 @@
 
       .token-icon-set {
         display: flex;
+        @media screen and (max-width: 600px) {
+          flex-direction: column;
+        }
         align-items: stretch;
```
Comment (daltonfury42) [inline simplq/src/components/pages/Admin/admin.module.scss:112]: https://user-images.githubusercontent.com/11256376/112712492-f8f6fd00-8ef5-11eb-9b38-4fb118995a69.mov

**Review by maaverik — APPROVED** [review]
